cuda_device_id: 0
method: fedavg
global_method: fedavg 
arch: FCBase
weight_decay: 1e-3 
gr_clipping_max_norm: 10 
global_epochs: 3 
alpha: 1 
mu: 0.001 
gamma: 0.9 
momentum: 0.0 
tau: 1.0 
lr: 1e-1 
mode: dirichlet 
dirichlet_alpha: 0.3  
participation_rate: 0.05
eval_path: Metrics/method
learning_rate_decay: 0.995 
entity: your_user_name 
set: CICIDS2017